# Generated by Django 2.1.7 on 2019-11-23 18:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0007_dilikes_like'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dilikes',
            new_name='Dilike',
        ),
    ]
